/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SafeScoutingRouteImport } from './routes/safe-scouting'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScoutIndexRouteImport } from './routes/scout/index'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ScoutSettingsRouteImport } from './routes/scout/settings'
import { Route as ScoutSelectionsRouteImport } from './routes/scout/selections'
import { Route as ScoutProfileRouteImport } from './routes/scout/profile'
import { Route as ScoutExploreRouteImport } from './routes/scout/explore'
import { Route as ResumeUserIdRouteImport } from './routes/resume.$userId'
import { Route as PlayerUploadRouteImport } from './routes/player/upload'
import { Route as PlayerSettingsRouteImport } from './routes/player/settings'
import { Route as PlayerProfileRouteImport } from './routes/player/profile'
import { Route as PlayerExploreRouteImport } from './routes/player/explore'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPanelRouteImport } from './routes/admin.panel'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as ScoutSettingsIndexRouteImport } from './routes/scout/settings.index'
import { Route as PlayerSettingsIndexRouteImport } from './routes/player/settings.index'
import { Route as ScoutSettingsVerificationRouteImport } from './routes/scout/settings.verification'
import { Route as ScoutSettingsPreferencesRouteImport } from './routes/scout/settings.preferences'
import { Route as PlayerSettingsVerifiedRouteImport } from './routes/player/settings.verified'
import { Route as PlayerSettingsTwoFactorRouteImport } from './routes/player/settings.two-factor'
import { Route as PlayerSettingsTimeRouteImport } from './routes/player/settings.time'
import { Route as PlayerSettingsThreadsRouteImport } from './routes/player/settings.threads'
import { Route as PlayerSettingsTagsRouteImport } from './routes/player/settings.tags'
import { Route as PlayerSettingsTabletsRouteImport } from './routes/player/settings.tablets'
import { Route as PlayerSettingsStoryRouteImport } from './routes/player/settings.story'
import { Route as PlayerSettingsSharingRouteImport } from './routes/player/settings.sharing'
import { Route as PlayerSettingsSessionsRouteImport } from './routes/player/settings.sessions'
import { Route as PlayerSettingsSavedRouteImport } from './routes/player/settings.saved'
import { Route as PlayerSettingsRestrictedRouteImport } from './routes/player/settings.restricted'
import { Route as PlayerSettingsPrivacyCenterRouteImport } from './routes/player/settings.privacy-center'
import { Route as PlayerSettingsPrivacyRouteImport } from './routes/player/settings.privacy'
import { Route as PlayerSettingsPersonalDetailsRouteImport } from './routes/player/settings.personal-details'
import { Route as PlayerSettingsPasswordRouteImport } from './routes/player/settings.password'
import { Route as PlayerSettingsOrdersRouteImport } from './routes/player/settings.orders'
import { Route as PlayerSettingsNotificationsRouteImport } from './routes/player/settings.notifications'
import { Route as PlayerSettingsMutedRouteImport } from './routes/player/settings.muted'
import { Route as PlayerSettingsMoreRouteImport } from './routes/player/settings.more'
import { Route as PlayerSettingsMessagesRouteImport } from './routes/player/settings.messages'
import { Route as PlayerSettingsLogoutRouteImport } from './routes/player/settings.logout'
import { Route as PlayerSettingsLimitRouteImport } from './routes/player/settings.limit'
import { Route as PlayerSettingsLanguageRouteImport } from './routes/player/settings.language'
import { Route as PlayerSettingsInviteRouteImport } from './routes/player/settings.invite'
import { Route as PlayerSettingsHiddenWordsRouteImport } from './routes/player/settings.hidden-words'
import { Route as PlayerSettingsHelpRouteImport } from './routes/player/settings.help'
import { Route as PlayerSettingsFriendsFeedRouteImport } from './routes/player/settings.friends-feed'
import { Route as PlayerSettingsFavoritesRouteImport } from './routes/player/settings.favorites'
import { Route as PlayerSettingsDownloadsRouteImport } from './routes/player/settings.downloads'
import { Route as PlayerSettingsDevicesRouteImport } from './routes/player/settings.devices'
import { Route as PlayerSettingsDataUsageRouteImport } from './routes/player/settings.data-usage'
import { Route as PlayerSettingsCrosspostingRouteImport } from './routes/player/settings.crossposting'
import { Route as PlayerSettingsCountsRouteImport } from './routes/player/settings.counts'
import { Route as PlayerSettingsContentPreferencesRouteImport } from './routes/player/settings.content-preferences'
import { Route as PlayerSettingsCommentsRouteImport } from './routes/player/settings.comments'
import { Route as PlayerSettingsCloseFriendsRouteImport } from './routes/player/settings.close-friends'
import { Route as PlayerSettingsBlockedRouteImport } from './routes/player/settings.blocked'
import { Route as PlayerSettingsArchiveRouteImport } from './routes/player/settings.archive'
import { Route as PlayerSettingsAppWebRouteImport } from './routes/player/settings.app-web'
import { Route as PlayerSettingsAiRouteImport } from './routes/player/settings.ai'
import { Route as PlayerSettingsAddAccountRouteImport } from './routes/player/settings.add-account'
import { Route as PlayerSettingsActivityRouteImport } from './routes/player/settings.activity'
import { Route as PlayerSettingsAccountsCenterRouteImport } from './routes/player/settings.accounts-center'
import { Route as PlayerSettingsAccountTypeRouteImport } from './routes/player/settings.account-type'
import { Route as PlayerSettingsAccountStatusRouteImport } from './routes/player/settings.account-status'
import { Route as PlayerSettingsAccessibilityRouteImport } from './routes/player/settings.accessibility'
import { Route as PlayerSettingsAboutRouteImport } from './routes/player/settings.about'

const SafeScoutingRoute = SafeScoutingRouteImport.update({
  id: '/safe-scouting',
  path: '/safe-scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutIndexRoute = ScoutIndexRouteImport.update({
  id: '/scout/',
  path: '/scout/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ScoutSettingsRoute = ScoutSettingsRouteImport.update({
  id: '/scout/settings',
  path: '/scout/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutSelectionsRoute = ScoutSelectionsRouteImport.update({
  id: '/scout/selections',
  path: '/scout/selections',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutProfileRoute = ScoutProfileRouteImport.update({
  id: '/scout/profile',
  path: '/scout/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutExploreRoute = ScoutExploreRouteImport.update({
  id: '/scout/explore',
  path: '/scout/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeUserIdRoute = ResumeUserIdRouteImport.update({
  id: '/resume/$userId',
  path: '/resume/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUploadRoute = PlayerUploadRouteImport.update({
  id: '/player/upload',
  path: '/player/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerSettingsRoute = PlayerSettingsRouteImport.update({
  id: '/player/settings',
  path: '/player/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerProfileRoute = PlayerProfileRouteImport.update({
  id: '/player/profile',
  path: '/player/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerExploreRoute = PlayerExploreRouteImport.update({
  id: '/player/explore',
  path: '/player/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const ScoutSettingsIndexRoute = ScoutSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoutSettingsRoute,
} as any)
const PlayerSettingsIndexRoute = PlayerSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const ScoutSettingsVerificationRoute =
  ScoutSettingsVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => ScoutSettingsRoute,
  } as any)
const ScoutSettingsPreferencesRoute =
  ScoutSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => ScoutSettingsRoute,
  } as any)
const PlayerSettingsVerifiedRoute = PlayerSettingsVerifiedRouteImport.update({
  id: '/verified',
  path: '/verified',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsTwoFactorRoute = PlayerSettingsTwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsTimeRoute = PlayerSettingsTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsThreadsRoute = PlayerSettingsThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsTagsRoute = PlayerSettingsTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsTabletsRoute = PlayerSettingsTabletsRouteImport.update({
  id: '/tablets',
  path: '/tablets',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsStoryRoute = PlayerSettingsStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsSharingRoute = PlayerSettingsSharingRouteImport.update({
  id: '/sharing',
  path: '/sharing',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsSessionsRoute = PlayerSettingsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsSavedRoute = PlayerSettingsSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsRestrictedRoute =
  PlayerSettingsRestrictedRouteImport.update({
    id: '/restricted',
    path: '/restricted',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsPrivacyCenterRoute =
  PlayerSettingsPrivacyCenterRouteImport.update({
    id: '/privacy-center',
    path: '/privacy-center',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsPrivacyRoute = PlayerSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsPersonalDetailsRoute =
  PlayerSettingsPersonalDetailsRouteImport.update({
    id: '/personal-details',
    path: '/personal-details',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsPasswordRoute = PlayerSettingsPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsOrdersRoute = PlayerSettingsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsNotificationsRoute =
  PlayerSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsMutedRoute = PlayerSettingsMutedRouteImport.update({
  id: '/muted',
  path: '/muted',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsMoreRoute = PlayerSettingsMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsMessagesRoute = PlayerSettingsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsLogoutRoute = PlayerSettingsLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsLimitRoute = PlayerSettingsLimitRouteImport.update({
  id: '/limit',
  path: '/limit',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsLanguageRoute = PlayerSettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsInviteRoute = PlayerSettingsInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsHiddenWordsRoute =
  PlayerSettingsHiddenWordsRouteImport.update({
    id: '/hidden-words',
    path: '/hidden-words',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsHelpRoute = PlayerSettingsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsFriendsFeedRoute =
  PlayerSettingsFriendsFeedRouteImport.update({
    id: '/friends-feed',
    path: '/friends-feed',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsFavoritesRoute = PlayerSettingsFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsDownloadsRoute = PlayerSettingsDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsDevicesRoute = PlayerSettingsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsDataUsageRoute = PlayerSettingsDataUsageRouteImport.update({
  id: '/data-usage',
  path: '/data-usage',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsCrosspostingRoute =
  PlayerSettingsCrosspostingRouteImport.update({
    id: '/crossposting',
    path: '/crossposting',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsCountsRoute = PlayerSettingsCountsRouteImport.update({
  id: '/counts',
  path: '/counts',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsContentPreferencesRoute =
  PlayerSettingsContentPreferencesRouteImport.update({
    id: '/content-preferences',
    path: '/content-preferences',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsCommentsRoute = PlayerSettingsCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsCloseFriendsRoute =
  PlayerSettingsCloseFriendsRouteImport.update({
    id: '/close-friends',
    path: '/close-friends',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsBlockedRoute = PlayerSettingsBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsArchiveRoute = PlayerSettingsArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsAppWebRoute = PlayerSettingsAppWebRouteImport.update({
  id: '/app-web',
  path: '/app-web',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsAiRoute = PlayerSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsAddAccountRoute =
  PlayerSettingsAddAccountRouteImport.update({
    id: '/add-account',
    path: '/add-account',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsActivityRoute = PlayerSettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PlayerSettingsRoute,
} as any)
const PlayerSettingsAccountsCenterRoute =
  PlayerSettingsAccountsCenterRouteImport.update({
    id: '/accounts-center',
    path: '/accounts-center',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsAccountTypeRoute =
  PlayerSettingsAccountTypeRouteImport.update({
    id: '/account-type',
    path: '/account-type',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsAccountStatusRoute =
  PlayerSettingsAccountStatusRouteImport.update({
    id: '/account-status',
    path: '/account-status',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsAccessibilityRoute =
  PlayerSettingsAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => PlayerSettingsRoute,
  } as any)
const PlayerSettingsAboutRoute = PlayerSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PlayerSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safe-scouting': typeof SafeScoutingRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/player/explore': typeof PlayerExploreRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/settings': typeof PlayerSettingsRouteWithChildren
  '/player/upload': typeof PlayerUploadRoute
  '/resume/$userId': typeof ResumeUserIdRoute
  '/scout/explore': typeof ScoutExploreRoute
  '/scout/profile': typeof ScoutProfileRoute
  '/scout/selections': typeof ScoutSelectionsRoute
  '/scout/settings': typeof ScoutSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/player/settings/about': typeof PlayerSettingsAboutRoute
  '/player/settings/accessibility': typeof PlayerSettingsAccessibilityRoute
  '/player/settings/account-status': typeof PlayerSettingsAccountStatusRoute
  '/player/settings/account-type': typeof PlayerSettingsAccountTypeRoute
  '/player/settings/accounts-center': typeof PlayerSettingsAccountsCenterRoute
  '/player/settings/activity': typeof PlayerSettingsActivityRoute
  '/player/settings/add-account': typeof PlayerSettingsAddAccountRoute
  '/player/settings/ai': typeof PlayerSettingsAiRoute
  '/player/settings/app-web': typeof PlayerSettingsAppWebRoute
  '/player/settings/archive': typeof PlayerSettingsArchiveRoute
  '/player/settings/blocked': typeof PlayerSettingsBlockedRoute
  '/player/settings/close-friends': typeof PlayerSettingsCloseFriendsRoute
  '/player/settings/comments': typeof PlayerSettingsCommentsRoute
  '/player/settings/content-preferences': typeof PlayerSettingsContentPreferencesRoute
  '/player/settings/counts': typeof PlayerSettingsCountsRoute
  '/player/settings/crossposting': typeof PlayerSettingsCrosspostingRoute
  '/player/settings/data-usage': typeof PlayerSettingsDataUsageRoute
  '/player/settings/devices': typeof PlayerSettingsDevicesRoute
  '/player/settings/downloads': typeof PlayerSettingsDownloadsRoute
  '/player/settings/favorites': typeof PlayerSettingsFavoritesRoute
  '/player/settings/friends-feed': typeof PlayerSettingsFriendsFeedRoute
  '/player/settings/help': typeof PlayerSettingsHelpRoute
  '/player/settings/hidden-words': typeof PlayerSettingsHiddenWordsRoute
  '/player/settings/invite': typeof PlayerSettingsInviteRoute
  '/player/settings/language': typeof PlayerSettingsLanguageRoute
  '/player/settings/limit': typeof PlayerSettingsLimitRoute
  '/player/settings/logout': typeof PlayerSettingsLogoutRoute
  '/player/settings/messages': typeof PlayerSettingsMessagesRoute
  '/player/settings/more': typeof PlayerSettingsMoreRoute
  '/player/settings/muted': typeof PlayerSettingsMutedRoute
  '/player/settings/notifications': typeof PlayerSettingsNotificationsRoute
  '/player/settings/orders': typeof PlayerSettingsOrdersRoute
  '/player/settings/password': typeof PlayerSettingsPasswordRoute
  '/player/settings/personal-details': typeof PlayerSettingsPersonalDetailsRoute
  '/player/settings/privacy': typeof PlayerSettingsPrivacyRoute
  '/player/settings/privacy-center': typeof PlayerSettingsPrivacyCenterRoute
  '/player/settings/restricted': typeof PlayerSettingsRestrictedRoute
  '/player/settings/saved': typeof PlayerSettingsSavedRoute
  '/player/settings/sessions': typeof PlayerSettingsSessionsRoute
  '/player/settings/sharing': typeof PlayerSettingsSharingRoute
  '/player/settings/story': typeof PlayerSettingsStoryRoute
  '/player/settings/tablets': typeof PlayerSettingsTabletsRoute
  '/player/settings/tags': typeof PlayerSettingsTagsRoute
  '/player/settings/threads': typeof PlayerSettingsThreadsRoute
  '/player/settings/time': typeof PlayerSettingsTimeRoute
  '/player/settings/two-factor': typeof PlayerSettingsTwoFactorRoute
  '/player/settings/verified': typeof PlayerSettingsVerifiedRoute
  '/scout/settings/preferences': typeof ScoutSettingsPreferencesRoute
  '/scout/settings/verification': typeof ScoutSettingsVerificationRoute
  '/player/settings/': typeof PlayerSettingsIndexRoute
  '/scout/settings/': typeof ScoutSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safe-scouting': typeof SafeScoutingRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/player/explore': typeof PlayerExploreRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/upload': typeof PlayerUploadRoute
  '/resume/$userId': typeof ResumeUserIdRoute
  '/scout/explore': typeof ScoutExploreRoute
  '/scout/profile': typeof ScoutProfileRoute
  '/scout/selections': typeof ScoutSelectionsRoute
  '/admin': typeof AdminIndexRoute
  '/player': typeof PlayerIndexRoute
  '/scout': typeof ScoutIndexRoute
  '/player/settings/about': typeof PlayerSettingsAboutRoute
  '/player/settings/accessibility': typeof PlayerSettingsAccessibilityRoute
  '/player/settings/account-status': typeof PlayerSettingsAccountStatusRoute
  '/player/settings/account-type': typeof PlayerSettingsAccountTypeRoute
  '/player/settings/accounts-center': typeof PlayerSettingsAccountsCenterRoute
  '/player/settings/activity': typeof PlayerSettingsActivityRoute
  '/player/settings/add-account': typeof PlayerSettingsAddAccountRoute
  '/player/settings/ai': typeof PlayerSettingsAiRoute
  '/player/settings/app-web': typeof PlayerSettingsAppWebRoute
  '/player/settings/archive': typeof PlayerSettingsArchiveRoute
  '/player/settings/blocked': typeof PlayerSettingsBlockedRoute
  '/player/settings/close-friends': typeof PlayerSettingsCloseFriendsRoute
  '/player/settings/comments': typeof PlayerSettingsCommentsRoute
  '/player/settings/content-preferences': typeof PlayerSettingsContentPreferencesRoute
  '/player/settings/counts': typeof PlayerSettingsCountsRoute
  '/player/settings/crossposting': typeof PlayerSettingsCrosspostingRoute
  '/player/settings/data-usage': typeof PlayerSettingsDataUsageRoute
  '/player/settings/devices': typeof PlayerSettingsDevicesRoute
  '/player/settings/downloads': typeof PlayerSettingsDownloadsRoute
  '/player/settings/favorites': typeof PlayerSettingsFavoritesRoute
  '/player/settings/friends-feed': typeof PlayerSettingsFriendsFeedRoute
  '/player/settings/help': typeof PlayerSettingsHelpRoute
  '/player/settings/hidden-words': typeof PlayerSettingsHiddenWordsRoute
  '/player/settings/invite': typeof PlayerSettingsInviteRoute
  '/player/settings/language': typeof PlayerSettingsLanguageRoute
  '/player/settings/limit': typeof PlayerSettingsLimitRoute
  '/player/settings/logout': typeof PlayerSettingsLogoutRoute
  '/player/settings/messages': typeof PlayerSettingsMessagesRoute
  '/player/settings/more': typeof PlayerSettingsMoreRoute
  '/player/settings/muted': typeof PlayerSettingsMutedRoute
  '/player/settings/notifications': typeof PlayerSettingsNotificationsRoute
  '/player/settings/orders': typeof PlayerSettingsOrdersRoute
  '/player/settings/password': typeof PlayerSettingsPasswordRoute
  '/player/settings/personal-details': typeof PlayerSettingsPersonalDetailsRoute
  '/player/settings/privacy': typeof PlayerSettingsPrivacyRoute
  '/player/settings/privacy-center': typeof PlayerSettingsPrivacyCenterRoute
  '/player/settings/restricted': typeof PlayerSettingsRestrictedRoute
  '/player/settings/saved': typeof PlayerSettingsSavedRoute
  '/player/settings/sessions': typeof PlayerSettingsSessionsRoute
  '/player/settings/sharing': typeof PlayerSettingsSharingRoute
  '/player/settings/story': typeof PlayerSettingsStoryRoute
  '/player/settings/tablets': typeof PlayerSettingsTabletsRoute
  '/player/settings/tags': typeof PlayerSettingsTagsRoute
  '/player/settings/threads': typeof PlayerSettingsThreadsRoute
  '/player/settings/time': typeof PlayerSettingsTimeRoute
  '/player/settings/two-factor': typeof PlayerSettingsTwoFactorRoute
  '/player/settings/verified': typeof PlayerSettingsVerifiedRoute
  '/scout/settings/preferences': typeof ScoutSettingsPreferencesRoute
  '/scout/settings/verification': typeof ScoutSettingsVerificationRoute
  '/player/settings': typeof PlayerSettingsIndexRoute
  '/scout/settings': typeof ScoutSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/mission': typeof MissionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/safe-scouting': typeof SafeScoutingRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/api/health': typeof ApiHealthRoute
  '/player/explore': typeof PlayerExploreRoute
  '/player/profile': typeof PlayerProfileRoute
  '/player/settings': typeof PlayerSettingsRouteWithChildren
  '/player/upload': typeof PlayerUploadRoute
  '/resume/$userId': typeof ResumeUserIdRoute
  '/scout/explore': typeof ScoutExploreRoute
  '/scout/profile': typeof ScoutProfileRoute
  '/scout/selections': typeof ScoutSelectionsRoute
  '/scout/settings': typeof ScoutSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/player/': typeof PlayerIndexRoute
  '/scout/': typeof ScoutIndexRoute
  '/player/settings/about': typeof PlayerSettingsAboutRoute
  '/player/settings/accessibility': typeof PlayerSettingsAccessibilityRoute
  '/player/settings/account-status': typeof PlayerSettingsAccountStatusRoute
  '/player/settings/account-type': typeof PlayerSettingsAccountTypeRoute
  '/player/settings/accounts-center': typeof PlayerSettingsAccountsCenterRoute
  '/player/settings/activity': typeof PlayerSettingsActivityRoute
  '/player/settings/add-account': typeof PlayerSettingsAddAccountRoute
  '/player/settings/ai': typeof PlayerSettingsAiRoute
  '/player/settings/app-web': typeof PlayerSettingsAppWebRoute
  '/player/settings/archive': typeof PlayerSettingsArchiveRoute
  '/player/settings/blocked': typeof PlayerSettingsBlockedRoute
  '/player/settings/close-friends': typeof PlayerSettingsCloseFriendsRoute
  '/player/settings/comments': typeof PlayerSettingsCommentsRoute
  '/player/settings/content-preferences': typeof PlayerSettingsContentPreferencesRoute
  '/player/settings/counts': typeof PlayerSettingsCountsRoute
  '/player/settings/crossposting': typeof PlayerSettingsCrosspostingRoute
  '/player/settings/data-usage': typeof PlayerSettingsDataUsageRoute
  '/player/settings/devices': typeof PlayerSettingsDevicesRoute
  '/player/settings/downloads': typeof PlayerSettingsDownloadsRoute
  '/player/settings/favorites': typeof PlayerSettingsFavoritesRoute
  '/player/settings/friends-feed': typeof PlayerSettingsFriendsFeedRoute
  '/player/settings/help': typeof PlayerSettingsHelpRoute
  '/player/settings/hidden-words': typeof PlayerSettingsHiddenWordsRoute
  '/player/settings/invite': typeof PlayerSettingsInviteRoute
  '/player/settings/language': typeof PlayerSettingsLanguageRoute
  '/player/settings/limit': typeof PlayerSettingsLimitRoute
  '/player/settings/logout': typeof PlayerSettingsLogoutRoute
  '/player/settings/messages': typeof PlayerSettingsMessagesRoute
  '/player/settings/more': typeof PlayerSettingsMoreRoute
  '/player/settings/muted': typeof PlayerSettingsMutedRoute
  '/player/settings/notifications': typeof PlayerSettingsNotificationsRoute
  '/player/settings/orders': typeof PlayerSettingsOrdersRoute
  '/player/settings/password': typeof PlayerSettingsPasswordRoute
  '/player/settings/personal-details': typeof PlayerSettingsPersonalDetailsRoute
  '/player/settings/privacy': typeof PlayerSettingsPrivacyRoute
  '/player/settings/privacy-center': typeof PlayerSettingsPrivacyCenterRoute
  '/player/settings/restricted': typeof PlayerSettingsRestrictedRoute
  '/player/settings/saved': typeof PlayerSettingsSavedRoute
  '/player/settings/sessions': typeof PlayerSettingsSessionsRoute
  '/player/settings/sharing': typeof PlayerSettingsSharingRoute
  '/player/settings/story': typeof PlayerSettingsStoryRoute
  '/player/settings/tablets': typeof PlayerSettingsTabletsRoute
  '/player/settings/tags': typeof PlayerSettingsTagsRoute
  '/player/settings/threads': typeof PlayerSettingsThreadsRoute
  '/player/settings/time': typeof PlayerSettingsTimeRoute
  '/player/settings/two-factor': typeof PlayerSettingsTwoFactorRoute
  '/player/settings/verified': typeof PlayerSettingsVerifiedRoute
  '/scout/settings/preferences': typeof ScoutSettingsPreferencesRoute
  '/scout/settings/verification': typeof ScoutSettingsVerificationRoute
  '/player/settings/': typeof PlayerSettingsIndexRoute
  '/scout/settings/': typeof ScoutSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/faq'
    | '/mission'
    | '/privacy-policy'
    | '/reset-password'
    | '/safe-scouting'
    | '/admin/moderation'
    | '/admin/panel'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/api/health'
    | '/player/explore'
    | '/player/profile'
    | '/player/settings'
    | '/player/upload'
    | '/resume/$userId'
    | '/scout/explore'
    | '/scout/profile'
    | '/scout/selections'
    | '/scout/settings'
    | '/admin/'
    | '/player/'
    | '/scout/'
    | '/player/settings/about'
    | '/player/settings/accessibility'
    | '/player/settings/account-status'
    | '/player/settings/account-type'
    | '/player/settings/accounts-center'
    | '/player/settings/activity'
    | '/player/settings/add-account'
    | '/player/settings/ai'
    | '/player/settings/app-web'
    | '/player/settings/archive'
    | '/player/settings/blocked'
    | '/player/settings/close-friends'
    | '/player/settings/comments'
    | '/player/settings/content-preferences'
    | '/player/settings/counts'
    | '/player/settings/crossposting'
    | '/player/settings/data-usage'
    | '/player/settings/devices'
    | '/player/settings/downloads'
    | '/player/settings/favorites'
    | '/player/settings/friends-feed'
    | '/player/settings/help'
    | '/player/settings/hidden-words'
    | '/player/settings/invite'
    | '/player/settings/language'
    | '/player/settings/limit'
    | '/player/settings/logout'
    | '/player/settings/messages'
    | '/player/settings/more'
    | '/player/settings/muted'
    | '/player/settings/notifications'
    | '/player/settings/orders'
    | '/player/settings/password'
    | '/player/settings/personal-details'
    | '/player/settings/privacy'
    | '/player/settings/privacy-center'
    | '/player/settings/restricted'
    | '/player/settings/saved'
    | '/player/settings/sessions'
    | '/player/settings/sharing'
    | '/player/settings/story'
    | '/player/settings/tablets'
    | '/player/settings/tags'
    | '/player/settings/threads'
    | '/player/settings/time'
    | '/player/settings/two-factor'
    | '/player/settings/verified'
    | '/scout/settings/preferences'
    | '/scout/settings/verification'
    | '/player/settings/'
    | '/scout/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/faq'
    | '/mission'
    | '/privacy-policy'
    | '/reset-password'
    | '/safe-scouting'
    | '/admin/moderation'
    | '/admin/panel'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/api/health'
    | '/player/explore'
    | '/player/profile'
    | '/player/upload'
    | '/resume/$userId'
    | '/scout/explore'
    | '/scout/profile'
    | '/scout/selections'
    | '/admin'
    | '/player'
    | '/scout'
    | '/player/settings/about'
    | '/player/settings/accessibility'
    | '/player/settings/account-status'
    | '/player/settings/account-type'
    | '/player/settings/accounts-center'
    | '/player/settings/activity'
    | '/player/settings/add-account'
    | '/player/settings/ai'
    | '/player/settings/app-web'
    | '/player/settings/archive'
    | '/player/settings/blocked'
    | '/player/settings/close-friends'
    | '/player/settings/comments'
    | '/player/settings/content-preferences'
    | '/player/settings/counts'
    | '/player/settings/crossposting'
    | '/player/settings/data-usage'
    | '/player/settings/devices'
    | '/player/settings/downloads'
    | '/player/settings/favorites'
    | '/player/settings/friends-feed'
    | '/player/settings/help'
    | '/player/settings/hidden-words'
    | '/player/settings/invite'
    | '/player/settings/language'
    | '/player/settings/limit'
    | '/player/settings/logout'
    | '/player/settings/messages'
    | '/player/settings/more'
    | '/player/settings/muted'
    | '/player/settings/notifications'
    | '/player/settings/orders'
    | '/player/settings/password'
    | '/player/settings/personal-details'
    | '/player/settings/privacy'
    | '/player/settings/privacy-center'
    | '/player/settings/restricted'
    | '/player/settings/saved'
    | '/player/settings/sessions'
    | '/player/settings/sharing'
    | '/player/settings/story'
    | '/player/settings/tablets'
    | '/player/settings/tags'
    | '/player/settings/threads'
    | '/player/settings/time'
    | '/player/settings/two-factor'
    | '/player/settings/verified'
    | '/scout/settings/preferences'
    | '/scout/settings/verification'
    | '/player/settings'
    | '/scout/settings'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/auth'
    | '/faq'
    | '/mission'
    | '/privacy-policy'
    | '/reset-password'
    | '/safe-scouting'
    | '/admin/moderation'
    | '/admin/panel'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/videos'
    | '/api/health'
    | '/player/explore'
    | '/player/profile'
    | '/player/settings'
    | '/player/upload'
    | '/resume/$userId'
    | '/scout/explore'
    | '/scout/profile'
    | '/scout/selections'
    | '/scout/settings'
    | '/admin/'
    | '/player/'
    | '/scout/'
    | '/player/settings/about'
    | '/player/settings/accessibility'
    | '/player/settings/account-status'
    | '/player/settings/account-type'
    | '/player/settings/accounts-center'
    | '/player/settings/activity'
    | '/player/settings/add-account'
    | '/player/settings/ai'
    | '/player/settings/app-web'
    | '/player/settings/archive'
    | '/player/settings/blocked'
    | '/player/settings/close-friends'
    | '/player/settings/comments'
    | '/player/settings/content-preferences'
    | '/player/settings/counts'
    | '/player/settings/crossposting'
    | '/player/settings/data-usage'
    | '/player/settings/devices'
    | '/player/settings/downloads'
    | '/player/settings/favorites'
    | '/player/settings/friends-feed'
    | '/player/settings/help'
    | '/player/settings/hidden-words'
    | '/player/settings/invite'
    | '/player/settings/language'
    | '/player/settings/limit'
    | '/player/settings/logout'
    | '/player/settings/messages'
    | '/player/settings/more'
    | '/player/settings/muted'
    | '/player/settings/notifications'
    | '/player/settings/orders'
    | '/player/settings/password'
    | '/player/settings/personal-details'
    | '/player/settings/privacy'
    | '/player/settings/privacy-center'
    | '/player/settings/restricted'
    | '/player/settings/saved'
    | '/player/settings/sessions'
    | '/player/settings/sharing'
    | '/player/settings/story'
    | '/player/settings/tablets'
    | '/player/settings/tags'
    | '/player/settings/threads'
    | '/player/settings/time'
    | '/player/settings/two-factor'
    | '/player/settings/verified'
    | '/scout/settings/preferences'
    | '/scout/settings/verification'
    | '/player/settings/'
    | '/scout/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  MissionRoute: typeof MissionRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SafeScoutingRoute: typeof SafeScoutingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PlayerExploreRoute: typeof PlayerExploreRoute
  PlayerProfileRoute: typeof PlayerProfileRoute
  PlayerSettingsRoute: typeof PlayerSettingsRouteWithChildren
  PlayerUploadRoute: typeof PlayerUploadRoute
  ResumeUserIdRoute: typeof ResumeUserIdRoute
  ScoutExploreRoute: typeof ScoutExploreRoute
  ScoutProfileRoute: typeof ScoutProfileRoute
  ScoutSelectionsRoute: typeof ScoutSelectionsRoute
  ScoutSettingsRoute: typeof ScoutSettingsRouteWithChildren
  PlayerIndexRoute: typeof PlayerIndexRoute
  ScoutIndexRoute: typeof ScoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/safe-scouting': {
      id: '/safe-scouting'
      path: '/safe-scouting'
      fullPath: '/safe-scouting'
      preLoaderRoute: typeof SafeScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/': {
      id: '/scout/'
      path: '/scout'
      fullPath: '/scout/'
      preLoaderRoute: typeof ScoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scout/settings': {
      id: '/scout/settings'
      path: '/scout/settings'
      fullPath: '/scout/settings'
      preLoaderRoute: typeof ScoutSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/selections': {
      id: '/scout/selections'
      path: '/scout/selections'
      fullPath: '/scout/selections'
      preLoaderRoute: typeof ScoutSelectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/profile': {
      id: '/scout/profile'
      path: '/scout/profile'
      fullPath: '/scout/profile'
      preLoaderRoute: typeof ScoutProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout/explore': {
      id: '/scout/explore'
      path: '/scout/explore'
      fullPath: '/scout/explore'
      preLoaderRoute: typeof ScoutExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume/$userId': {
      id: '/resume/$userId'
      path: '/resume/$userId'
      fullPath: '/resume/$userId'
      preLoaderRoute: typeof ResumeUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/upload': {
      id: '/player/upload'
      path: '/player/upload'
      fullPath: '/player/upload'
      preLoaderRoute: typeof PlayerUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/settings': {
      id: '/player/settings'
      path: '/player/settings'
      fullPath: '/player/settings'
      preLoaderRoute: typeof PlayerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/profile': {
      id: '/player/profile'
      path: '/player/profile'
      fullPath: '/player/profile'
      preLoaderRoute: typeof PlayerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/explore': {
      id: '/player/explore'
      path: '/player/explore'
      fullPath: '/player/explore'
      preLoaderRoute: typeof PlayerExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scout/settings/': {
      id: '/scout/settings/'
      path: '/'
      fullPath: '/scout/settings/'
      preLoaderRoute: typeof ScoutSettingsIndexRouteImport
      parentRoute: typeof ScoutSettingsRoute
    }
    '/player/settings/': {
      id: '/player/settings/'
      path: '/'
      fullPath: '/player/settings/'
      preLoaderRoute: typeof PlayerSettingsIndexRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/scout/settings/verification': {
      id: '/scout/settings/verification'
      path: '/verification'
      fullPath: '/scout/settings/verification'
      preLoaderRoute: typeof ScoutSettingsVerificationRouteImport
      parentRoute: typeof ScoutSettingsRoute
    }
    '/scout/settings/preferences': {
      id: '/scout/settings/preferences'
      path: '/preferences'
      fullPath: '/scout/settings/preferences'
      preLoaderRoute: typeof ScoutSettingsPreferencesRouteImport
      parentRoute: typeof ScoutSettingsRoute
    }
    '/player/settings/verified': {
      id: '/player/settings/verified'
      path: '/verified'
      fullPath: '/player/settings/verified'
      preLoaderRoute: typeof PlayerSettingsVerifiedRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/two-factor': {
      id: '/player/settings/two-factor'
      path: '/two-factor'
      fullPath: '/player/settings/two-factor'
      preLoaderRoute: typeof PlayerSettingsTwoFactorRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/time': {
      id: '/player/settings/time'
      path: '/time'
      fullPath: '/player/settings/time'
      preLoaderRoute: typeof PlayerSettingsTimeRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/threads': {
      id: '/player/settings/threads'
      path: '/threads'
      fullPath: '/player/settings/threads'
      preLoaderRoute: typeof PlayerSettingsThreadsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/tags': {
      id: '/player/settings/tags'
      path: '/tags'
      fullPath: '/player/settings/tags'
      preLoaderRoute: typeof PlayerSettingsTagsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/tablets': {
      id: '/player/settings/tablets'
      path: '/tablets'
      fullPath: '/player/settings/tablets'
      preLoaderRoute: typeof PlayerSettingsTabletsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/story': {
      id: '/player/settings/story'
      path: '/story'
      fullPath: '/player/settings/story'
      preLoaderRoute: typeof PlayerSettingsStoryRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/sharing': {
      id: '/player/settings/sharing'
      path: '/sharing'
      fullPath: '/player/settings/sharing'
      preLoaderRoute: typeof PlayerSettingsSharingRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/sessions': {
      id: '/player/settings/sessions'
      path: '/sessions'
      fullPath: '/player/settings/sessions'
      preLoaderRoute: typeof PlayerSettingsSessionsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/saved': {
      id: '/player/settings/saved'
      path: '/saved'
      fullPath: '/player/settings/saved'
      preLoaderRoute: typeof PlayerSettingsSavedRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/restricted': {
      id: '/player/settings/restricted'
      path: '/restricted'
      fullPath: '/player/settings/restricted'
      preLoaderRoute: typeof PlayerSettingsRestrictedRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/privacy-center': {
      id: '/player/settings/privacy-center'
      path: '/privacy-center'
      fullPath: '/player/settings/privacy-center'
      preLoaderRoute: typeof PlayerSettingsPrivacyCenterRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/privacy': {
      id: '/player/settings/privacy'
      path: '/privacy'
      fullPath: '/player/settings/privacy'
      preLoaderRoute: typeof PlayerSettingsPrivacyRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/personal-details': {
      id: '/player/settings/personal-details'
      path: '/personal-details'
      fullPath: '/player/settings/personal-details'
      preLoaderRoute: typeof PlayerSettingsPersonalDetailsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/password': {
      id: '/player/settings/password'
      path: '/password'
      fullPath: '/player/settings/password'
      preLoaderRoute: typeof PlayerSettingsPasswordRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/orders': {
      id: '/player/settings/orders'
      path: '/orders'
      fullPath: '/player/settings/orders'
      preLoaderRoute: typeof PlayerSettingsOrdersRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/notifications': {
      id: '/player/settings/notifications'
      path: '/notifications'
      fullPath: '/player/settings/notifications'
      preLoaderRoute: typeof PlayerSettingsNotificationsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/muted': {
      id: '/player/settings/muted'
      path: '/muted'
      fullPath: '/player/settings/muted'
      preLoaderRoute: typeof PlayerSettingsMutedRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/more': {
      id: '/player/settings/more'
      path: '/more'
      fullPath: '/player/settings/more'
      preLoaderRoute: typeof PlayerSettingsMoreRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/messages': {
      id: '/player/settings/messages'
      path: '/messages'
      fullPath: '/player/settings/messages'
      preLoaderRoute: typeof PlayerSettingsMessagesRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/logout': {
      id: '/player/settings/logout'
      path: '/logout'
      fullPath: '/player/settings/logout'
      preLoaderRoute: typeof PlayerSettingsLogoutRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/limit': {
      id: '/player/settings/limit'
      path: '/limit'
      fullPath: '/player/settings/limit'
      preLoaderRoute: typeof PlayerSettingsLimitRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/language': {
      id: '/player/settings/language'
      path: '/language'
      fullPath: '/player/settings/language'
      preLoaderRoute: typeof PlayerSettingsLanguageRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/invite': {
      id: '/player/settings/invite'
      path: '/invite'
      fullPath: '/player/settings/invite'
      preLoaderRoute: typeof PlayerSettingsInviteRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/hidden-words': {
      id: '/player/settings/hidden-words'
      path: '/hidden-words'
      fullPath: '/player/settings/hidden-words'
      preLoaderRoute: typeof PlayerSettingsHiddenWordsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/help': {
      id: '/player/settings/help'
      path: '/help'
      fullPath: '/player/settings/help'
      preLoaderRoute: typeof PlayerSettingsHelpRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/friends-feed': {
      id: '/player/settings/friends-feed'
      path: '/friends-feed'
      fullPath: '/player/settings/friends-feed'
      preLoaderRoute: typeof PlayerSettingsFriendsFeedRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/favorites': {
      id: '/player/settings/favorites'
      path: '/favorites'
      fullPath: '/player/settings/favorites'
      preLoaderRoute: typeof PlayerSettingsFavoritesRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/downloads': {
      id: '/player/settings/downloads'
      path: '/downloads'
      fullPath: '/player/settings/downloads'
      preLoaderRoute: typeof PlayerSettingsDownloadsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/devices': {
      id: '/player/settings/devices'
      path: '/devices'
      fullPath: '/player/settings/devices'
      preLoaderRoute: typeof PlayerSettingsDevicesRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/data-usage': {
      id: '/player/settings/data-usage'
      path: '/data-usage'
      fullPath: '/player/settings/data-usage'
      preLoaderRoute: typeof PlayerSettingsDataUsageRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/crossposting': {
      id: '/player/settings/crossposting'
      path: '/crossposting'
      fullPath: '/player/settings/crossposting'
      preLoaderRoute: typeof PlayerSettingsCrosspostingRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/counts': {
      id: '/player/settings/counts'
      path: '/counts'
      fullPath: '/player/settings/counts'
      preLoaderRoute: typeof PlayerSettingsCountsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/content-preferences': {
      id: '/player/settings/content-preferences'
      path: '/content-preferences'
      fullPath: '/player/settings/content-preferences'
      preLoaderRoute: typeof PlayerSettingsContentPreferencesRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/comments': {
      id: '/player/settings/comments'
      path: '/comments'
      fullPath: '/player/settings/comments'
      preLoaderRoute: typeof PlayerSettingsCommentsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/close-friends': {
      id: '/player/settings/close-friends'
      path: '/close-friends'
      fullPath: '/player/settings/close-friends'
      preLoaderRoute: typeof PlayerSettingsCloseFriendsRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/blocked': {
      id: '/player/settings/blocked'
      path: '/blocked'
      fullPath: '/player/settings/blocked'
      preLoaderRoute: typeof PlayerSettingsBlockedRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/archive': {
      id: '/player/settings/archive'
      path: '/archive'
      fullPath: '/player/settings/archive'
      preLoaderRoute: typeof PlayerSettingsArchiveRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/app-web': {
      id: '/player/settings/app-web'
      path: '/app-web'
      fullPath: '/player/settings/app-web'
      preLoaderRoute: typeof PlayerSettingsAppWebRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/ai': {
      id: '/player/settings/ai'
      path: '/ai'
      fullPath: '/player/settings/ai'
      preLoaderRoute: typeof PlayerSettingsAiRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/add-account': {
      id: '/player/settings/add-account'
      path: '/add-account'
      fullPath: '/player/settings/add-account'
      preLoaderRoute: typeof PlayerSettingsAddAccountRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/activity': {
      id: '/player/settings/activity'
      path: '/activity'
      fullPath: '/player/settings/activity'
      preLoaderRoute: typeof PlayerSettingsActivityRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/accounts-center': {
      id: '/player/settings/accounts-center'
      path: '/accounts-center'
      fullPath: '/player/settings/accounts-center'
      preLoaderRoute: typeof PlayerSettingsAccountsCenterRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/account-type': {
      id: '/player/settings/account-type'
      path: '/account-type'
      fullPath: '/player/settings/account-type'
      preLoaderRoute: typeof PlayerSettingsAccountTypeRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/account-status': {
      id: '/player/settings/account-status'
      path: '/account-status'
      fullPath: '/player/settings/account-status'
      preLoaderRoute: typeof PlayerSettingsAccountStatusRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/accessibility': {
      id: '/player/settings/accessibility'
      path: '/accessibility'
      fullPath: '/player/settings/accessibility'
      preLoaderRoute: typeof PlayerSettingsAccessibilityRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
    '/player/settings/about': {
      id: '/player/settings/about'
      path: '/about'
      fullPath: '/player/settings/about'
      preLoaderRoute: typeof PlayerSettingsAboutRouteImport
      parentRoute: typeof PlayerSettingsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminModerationRoute: AdminModerationRoute,
  AdminPanelRoute: AdminPanelRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PlayerSettingsRouteChildren {
  PlayerSettingsAboutRoute: typeof PlayerSettingsAboutRoute
  PlayerSettingsAccessibilityRoute: typeof PlayerSettingsAccessibilityRoute
  PlayerSettingsAccountStatusRoute: typeof PlayerSettingsAccountStatusRoute
  PlayerSettingsAccountTypeRoute: typeof PlayerSettingsAccountTypeRoute
  PlayerSettingsAccountsCenterRoute: typeof PlayerSettingsAccountsCenterRoute
  PlayerSettingsActivityRoute: typeof PlayerSettingsActivityRoute
  PlayerSettingsAddAccountRoute: typeof PlayerSettingsAddAccountRoute
  PlayerSettingsAiRoute: typeof PlayerSettingsAiRoute
  PlayerSettingsAppWebRoute: typeof PlayerSettingsAppWebRoute
  PlayerSettingsArchiveRoute: typeof PlayerSettingsArchiveRoute
  PlayerSettingsBlockedRoute: typeof PlayerSettingsBlockedRoute
  PlayerSettingsCloseFriendsRoute: typeof PlayerSettingsCloseFriendsRoute
  PlayerSettingsCommentsRoute: typeof PlayerSettingsCommentsRoute
  PlayerSettingsContentPreferencesRoute: typeof PlayerSettingsContentPreferencesRoute
  PlayerSettingsCountsRoute: typeof PlayerSettingsCountsRoute
  PlayerSettingsCrosspostingRoute: typeof PlayerSettingsCrosspostingRoute
  PlayerSettingsDataUsageRoute: typeof PlayerSettingsDataUsageRoute
  PlayerSettingsDevicesRoute: typeof PlayerSettingsDevicesRoute
  PlayerSettingsDownloadsRoute: typeof PlayerSettingsDownloadsRoute
  PlayerSettingsFavoritesRoute: typeof PlayerSettingsFavoritesRoute
  PlayerSettingsFriendsFeedRoute: typeof PlayerSettingsFriendsFeedRoute
  PlayerSettingsHelpRoute: typeof PlayerSettingsHelpRoute
  PlayerSettingsHiddenWordsRoute: typeof PlayerSettingsHiddenWordsRoute
  PlayerSettingsInviteRoute: typeof PlayerSettingsInviteRoute
  PlayerSettingsLanguageRoute: typeof PlayerSettingsLanguageRoute
  PlayerSettingsLimitRoute: typeof PlayerSettingsLimitRoute
  PlayerSettingsLogoutRoute: typeof PlayerSettingsLogoutRoute
  PlayerSettingsMessagesRoute: typeof PlayerSettingsMessagesRoute
  PlayerSettingsMoreRoute: typeof PlayerSettingsMoreRoute
  PlayerSettingsMutedRoute: typeof PlayerSettingsMutedRoute
  PlayerSettingsNotificationsRoute: typeof PlayerSettingsNotificationsRoute
  PlayerSettingsOrdersRoute: typeof PlayerSettingsOrdersRoute
  PlayerSettingsPasswordRoute: typeof PlayerSettingsPasswordRoute
  PlayerSettingsPersonalDetailsRoute: typeof PlayerSettingsPersonalDetailsRoute
  PlayerSettingsPrivacyRoute: typeof PlayerSettingsPrivacyRoute
  PlayerSettingsPrivacyCenterRoute: typeof PlayerSettingsPrivacyCenterRoute
  PlayerSettingsRestrictedRoute: typeof PlayerSettingsRestrictedRoute
  PlayerSettingsSavedRoute: typeof PlayerSettingsSavedRoute
  PlayerSettingsSessionsRoute: typeof PlayerSettingsSessionsRoute
  PlayerSettingsSharingRoute: typeof PlayerSettingsSharingRoute
  PlayerSettingsStoryRoute: typeof PlayerSettingsStoryRoute
  PlayerSettingsTabletsRoute: typeof PlayerSettingsTabletsRoute
  PlayerSettingsTagsRoute: typeof PlayerSettingsTagsRoute
  PlayerSettingsThreadsRoute: typeof PlayerSettingsThreadsRoute
  PlayerSettingsTimeRoute: typeof PlayerSettingsTimeRoute
  PlayerSettingsTwoFactorRoute: typeof PlayerSettingsTwoFactorRoute
  PlayerSettingsVerifiedRoute: typeof PlayerSettingsVerifiedRoute
  PlayerSettingsIndexRoute: typeof PlayerSettingsIndexRoute
}

const PlayerSettingsRouteChildren: PlayerSettingsRouteChildren = {
  PlayerSettingsAboutRoute: PlayerSettingsAboutRoute,
  PlayerSettingsAccessibilityRoute: PlayerSettingsAccessibilityRoute,
  PlayerSettingsAccountStatusRoute: PlayerSettingsAccountStatusRoute,
  PlayerSettingsAccountTypeRoute: PlayerSettingsAccountTypeRoute,
  PlayerSettingsAccountsCenterRoute: PlayerSettingsAccountsCenterRoute,
  PlayerSettingsActivityRoute: PlayerSettingsActivityRoute,
  PlayerSettingsAddAccountRoute: PlayerSettingsAddAccountRoute,
  PlayerSettingsAiRoute: PlayerSettingsAiRoute,
  PlayerSettingsAppWebRoute: PlayerSettingsAppWebRoute,
  PlayerSettingsArchiveRoute: PlayerSettingsArchiveRoute,
  PlayerSettingsBlockedRoute: PlayerSettingsBlockedRoute,
  PlayerSettingsCloseFriendsRoute: PlayerSettingsCloseFriendsRoute,
  PlayerSettingsCommentsRoute: PlayerSettingsCommentsRoute,
  PlayerSettingsContentPreferencesRoute: PlayerSettingsContentPreferencesRoute,
  PlayerSettingsCountsRoute: PlayerSettingsCountsRoute,
  PlayerSettingsCrosspostingRoute: PlayerSettingsCrosspostingRoute,
  PlayerSettingsDataUsageRoute: PlayerSettingsDataUsageRoute,
  PlayerSettingsDevicesRoute: PlayerSettingsDevicesRoute,
  PlayerSettingsDownloadsRoute: PlayerSettingsDownloadsRoute,
  PlayerSettingsFavoritesRoute: PlayerSettingsFavoritesRoute,
  PlayerSettingsFriendsFeedRoute: PlayerSettingsFriendsFeedRoute,
  PlayerSettingsHelpRoute: PlayerSettingsHelpRoute,
  PlayerSettingsHiddenWordsRoute: PlayerSettingsHiddenWordsRoute,
  PlayerSettingsInviteRoute: PlayerSettingsInviteRoute,
  PlayerSettingsLanguageRoute: PlayerSettingsLanguageRoute,
  PlayerSettingsLimitRoute: PlayerSettingsLimitRoute,
  PlayerSettingsLogoutRoute: PlayerSettingsLogoutRoute,
  PlayerSettingsMessagesRoute: PlayerSettingsMessagesRoute,
  PlayerSettingsMoreRoute: PlayerSettingsMoreRoute,
  PlayerSettingsMutedRoute: PlayerSettingsMutedRoute,
  PlayerSettingsNotificationsRoute: PlayerSettingsNotificationsRoute,
  PlayerSettingsOrdersRoute: PlayerSettingsOrdersRoute,
  PlayerSettingsPasswordRoute: PlayerSettingsPasswordRoute,
  PlayerSettingsPersonalDetailsRoute: PlayerSettingsPersonalDetailsRoute,
  PlayerSettingsPrivacyRoute: PlayerSettingsPrivacyRoute,
  PlayerSettingsPrivacyCenterRoute: PlayerSettingsPrivacyCenterRoute,
  PlayerSettingsRestrictedRoute: PlayerSettingsRestrictedRoute,
  PlayerSettingsSavedRoute: PlayerSettingsSavedRoute,
  PlayerSettingsSessionsRoute: PlayerSettingsSessionsRoute,
  PlayerSettingsSharingRoute: PlayerSettingsSharingRoute,
  PlayerSettingsStoryRoute: PlayerSettingsStoryRoute,
  PlayerSettingsTabletsRoute: PlayerSettingsTabletsRoute,
  PlayerSettingsTagsRoute: PlayerSettingsTagsRoute,
  PlayerSettingsThreadsRoute: PlayerSettingsThreadsRoute,
  PlayerSettingsTimeRoute: PlayerSettingsTimeRoute,
  PlayerSettingsTwoFactorRoute: PlayerSettingsTwoFactorRoute,
  PlayerSettingsVerifiedRoute: PlayerSettingsVerifiedRoute,
  PlayerSettingsIndexRoute: PlayerSettingsIndexRoute,
}

const PlayerSettingsRouteWithChildren = PlayerSettingsRoute._addFileChildren(
  PlayerSettingsRouteChildren,
)

interface ScoutSettingsRouteChildren {
  ScoutSettingsPreferencesRoute: typeof ScoutSettingsPreferencesRoute
  ScoutSettingsVerificationRoute: typeof ScoutSettingsVerificationRoute
  ScoutSettingsIndexRoute: typeof ScoutSettingsIndexRoute
}

const ScoutSettingsRouteChildren: ScoutSettingsRouteChildren = {
  ScoutSettingsPreferencesRoute: ScoutSettingsPreferencesRoute,
  ScoutSettingsVerificationRoute: ScoutSettingsVerificationRoute,
  ScoutSettingsIndexRoute: ScoutSettingsIndexRoute,
}

const ScoutSettingsRouteWithChildren = ScoutSettingsRoute._addFileChildren(
  ScoutSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  MissionRoute: MissionRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SafeScoutingRoute: SafeScoutingRoute,
  ApiHealthRoute: ApiHealthRoute,
  PlayerExploreRoute: PlayerExploreRoute,
  PlayerProfileRoute: PlayerProfileRoute,
  PlayerSettingsRoute: PlayerSettingsRouteWithChildren,
  PlayerUploadRoute: PlayerUploadRoute,
  ResumeUserIdRoute: ResumeUserIdRoute,
  ScoutExploreRoute: ScoutExploreRoute,
  ScoutProfileRoute: ScoutProfileRoute,
  ScoutSelectionsRoute: ScoutSelectionsRoute,
  ScoutSettingsRoute: ScoutSettingsRouteWithChildren,
  PlayerIndexRoute: PlayerIndexRoute,
  ScoutIndexRoute: ScoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
